# 私有源
source 'https://github.com/burning-git/volcengine-specs.git'
# CocoaPods 官方源
source 'https://cdn.cocoapods.org/'

use_frameworks! :linkage => :static

platform :ios, '12.0'

target 'BRShowVideoSDKBridge_Example' do
  pod 'BRShowVideoSDKBridge', :path => '../'

  target 'BRShowVideoSDKBridge_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
